# Generated by Django 2.2.2 on 2019-07-14 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190715_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='label',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
